services:
  hackathon_base:
    container_name: hackathon_base
    build: .
    ports:
      - 80:80
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80"
    environment:
      APP_NAME: "hackathon_base"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=hackathon
    expose:
      - 5432
volumes:
  postgres_data: